Repository seanmgd/sinistre-eshop, pull requests merged in 2020-11, with the labels that each got.

#8 fix-pageTitle-snapshots
  src/components/PageTitle/__snapshots__/PageTitle.test.js.snap
Labels: fixup

#6 feat(Input): Creation of the Input component
  src/components/Input/Input.js
  src/components/Input/Input.stories.js
  src/components/Input/index.js
  src/components/Input/input.styles.js
  src/components/index.js
Labels: new component

#5 feat(button): add checkbox component w/ storybook
  src/components/Checkbox/Checkbox.js
  src/components/Checkbox/Checkbox.stories.js
  src/components/Checkbox/Checkbox.test.js
  src/components/Checkbox/__snapshots__/Checkbox.test.js.snap
  src/components/Checkbox/index.js
  src/components/index.js
Labels: new component

#11 rb-navbar
  .prettierrc.json
  src/app/App.js
  src/constants/devices.js
  src/layout/Layout/Layout.js
  src/layout/Layout/Layout.style.js
  src/layout/Layout/index.js
  src/layout/Navbar/Burger.js
  src/layout/Navbar/Burger.style.js
  src/layout/Navbar/Navbar.js
  src/layout/Navbar/Navbar.style.js
  src/layout/Navbar/index.js
  src/layout/index.js
Labels: new component

#10 feat(api): add_api_architecture
  .env
  public/locales/en/translation.json
  public/locales/fr/translation.json
  src/app/App.js
  src/layout/Navbar/Navbar.js
  src/pages/Artist/Artist.js
  src/pages/Artists/Artists.js
  src/pages/Product/Product.js
  src/pages/Products/Products.js
  src/pages/Video/Video.js
  src/pages/Videos/Videos.js
  src/services/artists/query.js
  src/services/products/query.js
  src/services/videos/query.js
Labels: enhancement

#13 feat(theme): add theme switch mode
  src/AppProviders.js
  src/components/Button/Button.js
  src/components/Button/__snapshots__/Button.test.js.snap
  src/contexts/themeSwitcher.js
  src/pages/Home/Home.js
  src/renderTest.js
  src/styles/globalStyles.js
  src/styles/theme.js
Labels: feature

#7 feat(cardItem): add Card item w/ storybook
  src/app/App.js
  src/components/CardItem/CardItem.js
  src/components/CardItem/CardItem.stories.js
  src/components/CardItem/CardItem.styles.js
  src/components/CardItem/CardItem.test.js
  src/components/CardItem/__snapshots__/CardItem.test.js.snap
  src/components/CardItem/index.js
  src/components/index.js
  src/pages/Artist/Artist.js
  src/pages/Artist/Artist.styles.js
  src/pages/Product/Product.js
  src/pages/Video/Video.js
Labels: new component

#12 feat(ToastNotification): add ToastNotification /w storybook
  package.json
  src/components/ToastNotification/ToastNotification.js
  src/components/ToastNotification/ToastNotification.stories.js
  src/components/ToastNotification/ToastNotification.test.js
  src/components/ToastNotification/__snapshots__/ToastNotification.test.js.snap
  src/components/ToastNotification/index.js
  src/components/index.js
  yarn.lock
Labels: new component
